import { useMemo, useRef } from 'react';
import { useFrame, useThree } from '@react-three/fiber';
import { Float, Sparkles } from '@react-three/drei';
import * as THREE from 'three';
const clamp=(v:number)=>Math.min(1,Math.max(0,v));
function Pillar({x,z}:{x:number;z:number}){return <mesh position={[x,3,z]}><boxGeometry args={[.45,6,.45]}/><meshStandardMaterial color="#24251f" roughness={.7}/></mesh>}
function Ball({p}:{p:[number,number,number]}){return <Float speed={1.4} floatIntensity={.35}><mesh position={p}><sphereGeometry args={[.16,20,20]}/><meshStandardMaterial color="#d9e36b" roughness={.6}/></mesh></Float>}
function Racket({p}:{p:[number,number,number]}){return <group position={p} rotation={[.2,.3,.2]}><mesh rotation={[Math.PI/2,0,0]}><torusGeometry args={[.65,.07,10,32]}/><meshStandardMaterial color="#b8b4a5" metalness={.2}/></mesh><mesh position={[0,-.85,0]}><cylinderGeometry args={[.055,.055,1.7,10]}/><meshStandardMaterial color="#292a24"/></mesh></group>}
function Stadium(){const seats=useMemo(()=>Array.from({length:160},(_,i)=>{const a=i/160*Math.PI*2;const r=20+(i%5)*2.5;return [Math.cos(a)*r,1.2+((i%5)*.8),Math.sin(a)*r] as [number,number,number]}),[]);return <group position={[0,0,-128]}><mesh rotation={[-Math.PI/2,0,0]}><circleGeometry args={[34,64]}/><meshStandardMaterial color="#11120f" roughness={.9}/></mesh>{seats.map((p,i)=><mesh key={i} position={p}><boxGeometry args={[1,.55,1.3]}/><meshStandardMaterial color="#2b2d27"/></mesh>)}<mesh position={[0,.15,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[18,36]}/><meshStandardMaterial color="#55715a" roughness={.8}/></mesh>{[-17.1,-8.5,0,8.5,17.1].map(z=><mesh key={z} position={[0,.2,z]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[16.5,.035]}/><meshBasicMaterial color="#eee9d7"/></mesh>)}<mesh position={[0,.2,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[.035,36]}/><meshBasicMaterial color="#eee9d7"/></mesh><mesh position={[0,.65,0]}><boxGeometry args={[16.8,.08,.08]}/><meshBasicMaterial color="#eee9d7"/></mesh><mesh position={[0,5.4,0]}><torusGeometry args={[31,.12,10,96]}/><meshStandardMaterial color="#55584e" metalness={.25}/></mesh><Ball p={[4,.7,-5]}/></group>}
export function Scene({progress}:{progress:number}){const {camera}=useThree();const pos=useRef(new THREE.Vector3(0,2.1,8));const mouse=useRef({x:0,y:0});useMemo(()=>{const f=(e:PointerEvent)=>{mouse.current.x=(e.clientX/innerWidth-.5)*2;mouse.current.y=(e.clientY/innerHeight-.5)*2};addEventListener('pointermove',f);return()=>removeEventListener('pointermove',f)},[]);useFrame((_,dt)=>{const p=clamp(progress),reveal=clamp((p-.72)/.28),z=THREE.MathUtils.lerp(8,-114,Math.min(1,p/.82)),y=2.15+reveal*.75;pos.current.lerp(new THREE.Vector3(mouse.current.x*.3,y,z),1-Math.pow(.001,dt));camera.position.copy(pos.current);camera.lookAt(mouse.current.x*.12,2.3+reveal*.3,z-11-reveal*9)});const bays=Array.from({length:14},(_,i)=>-i*10-3);return <><color attach="background" args={['#0d0e0c']}/><fog attach="fog" args={['#0d0e0c',18,160]}/><ambientLight intensity={.55}/><directionalLight position={[8,12,8]} intensity={1.5}/><pointLight position={[0,4,-20]} intensity={4} distance={24} color="#e8d1a5"/><mesh position={[0,-.12,-64]}><boxGeometry args={[10,.24,132]}/><meshStandardMaterial color="#171814" roughness={.9}/></mesh><mesh position={[-5.1,3,-64]}><boxGeometry args={[.24,6,132]}/><meshStandardMaterial color="#11120f"/></mesh><mesh position={[5.1,3,-64]}><boxGeometry args={[.24,6,132]}/><meshStandardMaterial color="#11120f"/></mesh>{bays.map(z=><group key={z}><Pillar x={-4.6} z={z}/><Pillar x={4.6} z={z}/><mesh position={[0,4.9,z]}><boxGeometry args={[.07,.05,6.5]}/><meshBasicMaterial color="#f1d7a5"/></mesh></group>)}<Racket p={[4.1,2.5,-34]}/><Racket p={[-4.1,2.3,-67]}/><Ball p={[3.8,1.4,-22]}/><Ball p={[-3.9,1.7,-57]}/><Stadium/><Sparkles count={80} scale={[9,5,130]} position={[0,2,-62]} size={1.2} speed={.1} opacity={.25}/></>}
